spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: S2O23DXoDHfy4teiLNEE
            client-secret:
            redirect-uri: http://localhost:8080/auth/naver/callback
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 89fd7e95d907a1d6bcd86e5241d89b8f
            client-secret:
            redirect-uri: http://localhost:8080/auth/kakao/callback
          google:
            client-id: 101338795971-t4gs0d7nc2mat8pb2305pnbh01h616a2.apps.googleusercontent.com
            client-secret:
            redirect-uri: http://localhost:8080/auth/google/callback
            scope: https%3A//www.googleapis.com/auth/drive.metadata.readonly
        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/auth/userinfo.profile
