spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: id
            client-secret: pw
            redirect-uri: http://localhost:8080/auth/naver/callback
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: id
            client-secret: pw
            redirect-uri: http://localhost:8080/auth/kakao/callback
            authorization-grant-type: authorization_code
          google:
            client-id: id
            client-secret: pw
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/auth/userinfo.profile

logging:
  level:
    root: info