spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6379
  session:
    redis:
      namespace: toy:session
  profiles:
    include: "oauth"

logging:
  level:
    org.apache.coyote.http11: debug
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    session:
      cookie:
        name: toyLoginSession


